INSERT INTO nacionalidad (pais, nacionalidad) VALUES
('Afganistán', 'Afgano/a'),
('Albania', 'Albanés/a'),
('Alemania', 'Alemán/a'),
('Andorra', 'Andorrano/a'),
('Angola', 'Angoleño/a'),
('Antigua y Barbuda', 'Antiguano/a y Barbudense'),
('Arabia Saudita', 'Saudí'),
('Argelia', 'Argelino/a'),
('Argentina', 'Argentino/a'),
('Armenia', 'Armenio/a'),
('Australia', 'Australiano/a'),
('Austria', 'Austriaco/a'),
('Azerbaiyán', 'Azerbaiyano/a'),
('Bahamas', 'Bahameño/a'),
('Bangladés', 'Bangladesí'),
('Barbados', 'Barbadense'),
('Baréin', 'Bareiní'),
('Bélgica', 'Belga'),
('Belice', 'Beliceño/a'),
('Benín', 'Beninés/a'),
('Bielorrusia', 'Bielorruso/a'),
('Birmania', 'Birmano/a'),
('Bolivia', 'Boliviano/a'),
('Bosnia y Herzegovina', 'Bosnio/a'),
('Botsuana', 'Botsuano/a'),
('Brasil', 'Brasileño/a'),
('Brunéi', 'Bruneano/a'),
('Bulgaria', 'Búlgaro/a'),
('Burkina Faso', 'Burkinés/a'),
('Burundi', 'Burundés/a'),
('Bután', 'Butanés/a'),
('Cabo Verde', 'Caboverdiano/a'),
('Camboya', 'Camboyano/a'),
('Camerún', 'Camerunés/a'),
('Canadá', 'Canadiense'),
('Catar', 'Catarí'),
('Chad', 'Chadiano/a'),
('Chile', 'Chileno/a'),
('China', 'Chino/a'),
('Chipre', 'Chipriota'),
('Ciudad del Vaticano', 'Vaticano/a'),
('Colombia', 'Colombiano/a'),
('Comoras', 'Comorense'),
('Corea del Norte', 'Norcoreano/a'),
('Corea del Sur', 'Surcoreano/a'),
('Costa de Marfil', 'Marfileño/a'),
('Costa Rica', 'Costarricense'),
('Croacia', 'Croata'),
('Cuba', 'Cubano/a'),
('Dinamarca', 'Danés/a'),
('Dominica', 'Dominiqués/a'),
('Ecuador', 'Ecuatoriano/a'),
('Egipto', 'Egipcio/a'),
('El Salvador', 'Salvadoreño/a'),
('Emiratos Árabes Unidos', 'Emiratí'),
('Eritrea', 'Eritreo/a'),
('Eslovaquia', 'Eslovaco/a'),
('Eslovenia', 'Esloveno/a'),
('España', 'Español/a'),
('Estados Unidos', 'Estadounidense'),
('Estonia', 'Estonio/a'),
('Etiopía', 'Etíope'),
('Filipinas', 'Filipino/a'),
('Finlandia', 'Finlandés/a'),
('Fiyi', 'Fiyiano/a'),
('Francia', 'Francés/a'),
('Gabón', 'Gabonés/a'),
('Gambia', 'Gambiano/a'),
('Georgia', 'Georgiano/a'),
('Ghana', 'Ghanés/a'),
('Granada', 'Granadino/a'),
('Grecia', 'Griego/a'),
('Guatemala', 'Guatemalteco/a'),
('Guinea', 'Guineano/a'),
('Guinea-Bisáu', 'Bisauguineano/a'),
('Guinea Ecuatorial', 'Ecuatoguineano/a'),
('Guyana', 'Guyanés/a'),
('Haití', 'Haitiano/a'),
('Honduras', 'Hondureño/a'),
('Hungría', 'Húngaro/a'),
('India', 'Indio/a'),
('Indonesia', 'Indonesio/a'),
('Irak', 'Iraquí'),
('Irán', 'Iraní'),
('Irlanda', 'Irlandés/a'),
('Islandia', 'Islandés/a'),
('Islas Marshall', 'Marshallés/a'),
('Islas Salomón', 'Salomonense'),
('Israel', 'Israelí'),
('Italia', 'Italiano/a'),
('Jamaica', 'Jamaicano/a'),
('Japón', 'Japonés/a'),
('Jordania', 'Jordano/a'),
('Kazajistán', 'Kazajo/a'),
('Kenia', 'Keniano/a'),
('Kirguistán', 'Kirguís'),
('Kiribati', 'Kiribatiano/a'),
('Kuwait', 'Kuwaití'),
('Laos', 'Laosiano/a'),
('Lesoto', 'Lesotense'),
('Letonia', 'Letón/a'),
('Líbano', 'Libanés/a'),
('Liberia', 'Liberiano/a'),
('Libia', 'Libio/a'),
('Liechtenstein', 'Liechtensteiniano/a'),
('Lituania', 'Lituano/a'),
('Luxemburgo', 'Luxemburgués/a'),
('Macedonia del Norte', 'Macedonio/a'),
('Madagascar', 'Malagache'),
('Malasia', 'Malasio/a'),
('Malaui', 'Malauí'),
('Maldivas', 'Maldivo/a'),
('Malí', 'Maliense'),
('Malta', 'Maltés/a'),
('Marruecos', 'Marroquí'),
('Mauricio', 'Mauriciano/a'),
('Mauritania', 'Mauritano/a'),
('México', 'Mexicano/a'),
('Micronesia', 'Micronesio/a'),
('Moldavia', 'Moldavo/a'),
('Mónaco', 'Monegasco/a'),
('Mongolia', 'Mongol/a'),
('Montenegro', 'Montenegrino/a'),
('Mozambique', 'Mozambiqueño/a'),
('Namibia', 'Namibio/a'),
('Nauru', 'Nauruano/a'),
('Nepal', 'Nepalí'),
('Nicaragua', 'Nicaragüense'),
('Níger', 'Nigerino/a'),
('Nigeria', 'Nigeriano/a'),
('Noruega', 'Noruego/a'),
('Nueva Zelanda', 'Neozelandés/a'),
('Omán', 'Omaní'),
('Países Bajos', 'Neerlandés/a'),
('Pakistán', 'Pakistaní'),
('Palaos', 'Palauano/a'),
('Panamá', 'Panameño/a'),
('Papúa Nueva Guinea', 'Papú/a'),
('Paraguay', 'Paraguayo/a'),
('Perú', 'Peruano/a'),
('Polonia', 'Polaco/a'),
('Portugal', 'Portugués/a'),
('Reino Unido', 'Británico/a'),
('República Centroafricana', 'Centroafricano/a'),
('República Checa', 'Checo/a'),
('República Democrática del Congo', 'Congoleño/a'),
('República del Congo', 'Congoleño/a'),
('República Dominicana', 'Dominicano/a'),
('Ruanda', 'Ruandés/a'),
('Rumania', 'Rumano/a'),
('Rusia', 'Ruso/a'),
('Samoa', 'Samoano/a'),
('San Cristóbal y Nieves', 'Sancristobaleño/a'),
('San Marino', 'Sanmarinense'),
('San Vicente y las Granadinas', 'Sanvicentino/a'),
('Santa Lucía', 'Santalucense'),
('Santo Tomé y Príncipe', 'Santomense'),
('Senegal', 'Senegalés/a'),
('Serbia', 'Serbio/a'),
('Seychelles', 'Seychellense'),
('Sierra Leona', 'Sierraleonés/a'),
('Singapur', 'Singapurense'),
('Siria', 'Sirio/a'),
('Somalia', 'Somalí'),
('Sri Lanka', 'Ceilanés/a'),
('Suazilandia', 'Suazi'),
('Sudáfrica', 'Sudafricano/a'),
('Sudán', 'Sudanés/a'),
('Sudán del Sur', 'Sursudanés/a'),
('Suecia', 'Sueco/a'),
('Suiza', 'Suizo/a'),
('Surinam', 'Surinamés/a'),
('Tailandia', 'Tailandés/a'),
('Tanzania', 'Tanzano/a'),
('Tayikistán', 'Tayiko/a'),
('Timor Oriental', 'Timorense'),
('Togo', 'Togolés/a'),
('Tonga', 'Tongano/a'),
('Trinidad y Tobago', 'Trinitense y Tobaguense'),
('Túnez', 'Tunecino/a'),
('Turkmenistán', 'Turkmeno/a'),
('Turquía', 'Turco/a'),
('Tuvalu', 'Tuvaluano/a'),
('Ucrania', 'Ucraniano/a'),
('Uganda', 'Ugandés/a'),
('Uruguay', 'Uruguayo/a'),
('Uzbekistán', 'Uzbeko/a'),
('Vanuatu', 'Vanuatuense'),
('Venezuela', 'Venezolano/a'),
('Vietnam', 'Vietnamita'),
('Yemen', 'Yemení'),
('Yibuti', 'Yibutiano/a'),
('Zambia', 'Zambiano/a'),
('Zimbabue', 'Zimbabuense');